### ISSUE TITLE
Dummy app does not start

### ISSUE THREAD

**Issue by psbanka** [shayanypn/ember-cli-masonry-grid#2]
After performing an `npm install` and a `bower install`, running `npm start` yields the following:

```bash
~/play/ember-cli-masonry-grid [master|✔]
15:23 $ npm start

> ember-cli-masonry-grid@0.0.7 start /Users/pbanka/play/ember-cli-masonry-grid
> ember server

Livereload server on http://localhost:49154
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '/Users/pbanka/play/ember-cli-masonry-grid/tmp/source_map_concat-input_base_path-g9uuUJYq.tmp/bower_components/masonry/dist/masonry.pkgd.min.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at SourceMap.addFile (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/pbanka/play/ember-cli-masonry-grid/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/pbanka/play/ember-cli-masonry-grid/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/rsvp/dist/rsvp.js:1077:33)

The broccoli plugin was instantiated at:
    at Concat.Plugin (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/broccoli-concat/index.js:26:10)
    at EmberAddon._concatFiles (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/ember-cli/lib/broccoli/ember-app.js:432:12)
    at EmberAddon.javascript (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/ember-cli/lib/broccoli/ember-app.js:1277:14)
    at EmberAddon.toArray (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/ember-cli/lib/broccoli/ember-app.js:1664:12)
    at EmberAddon.toTree (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/ember-cli/lib/broccoli/ember-app.js:1686:38)
    at module.exports (/Users/pbanka/play/ember-cli-masonry-grid/ember-cli-build.js:16:14)
    at Builder.setupBroccoliBuilder (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/Users/pbanka/play/ember-cli-masonry-grid/node_modules/ember-cli/lib/models/builder.js:30:10)
```
Any suggestions?

**Comment by shayanypn** [comment]
You are right, I fix this issue on v.0.0.8.
